/*
 * SelectByChecks.java
 *
 * Created on 04 October 2002, 21:27
 */

package com.pcmsolutions.util;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author  pmeehan
 */
public class SelectByChecks extends javax.swing.JDialog {
    JScrollPane scrollpane;
    List vChecks = new ArrayList();
    Object[] options;
    List selected;

    /** Creates new form SelectByChecks */
    public SelectByChecks(java.awt.Frame parent, boolean modal, Object[] options, List selected, String title) {
        super(parent, modal);
        setTitle(title);

        this.options = options;
        this.selected = selected;

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButtonPanel = new javax.swing.JPanel();
        jbSelectAll = new javax.swing.JButton();
        jbDone = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jCheckBoxPanel = new javax.swing.JPanel();

        //getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationRelativeTo(getOwner());
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jbSelectAll.setText("SelectAll");
        jbSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelectAllActionPerformed(evt);
            }
        });

        jButtonPanel.add(jbSelectAll);

        jbDone.setText("Done");
        jbDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDoneActionPerformed(evt);
            }
        });

        jButtonPanel.add(jbDone);

        //getContentPane().addDesktopElement(jButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 410, 60));

        jCheckBoxPanel.setLayout(new java.awt.GridLayout(-1, 1));

        for (int row = 0; row < options.length; row++) {
            JCheckBox chk = new JCheckBox(options[row].toString());
            vChecks.add(chk);
            jCheckBoxPanel.add(chk);
        }
        jScrollPane.setViewportView(jCheckBoxPanel);

        //getContentPane().addDesktopElement(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 240));

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize(new java.awt.Dimension(300, 300));
        setLocation((screenSize.width - 300) / 2, (screenSize.height - 300) / 2);
    }//GEN-END:initComponents

    private void jbDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDoneActionPerformed
        // Add your handling code here:
        for (int n = 0; n < vChecks.size(); n++) {
            if (((JCheckBox) (vChecks.get(n))).isSelected()) {
                selected.add(options[n]);
            }
        }
        setVisible(false);
        dispose();

    }//GEN-LAST:event_jbDoneActionPerformed

    private void jbSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelectAllActionPerformed
        // Add your handling code here:
        for (int n = 0; n < vChecks.size(); n++) {
            ((JCheckBox) (vChecks.get(n))).setSelected(true);
        }
    }//GEN-LAST:event_jbSelectAllActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jButtonPanel;
    private javax.swing.JButton jbSelectAll;
    private javax.swing.JButton jbDone;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JPanel jCheckBoxPanel;
    // End of variables declaration//GEN-END:variables

}
